dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  google_mlkit_face_detection: ^0.11.0
  tflite_flutter: ^0.10.4
  image: ^4.1.3 # Important: Check version compatibility
  path_provider: ^2.1.1
  
assets:
  - assets/sight_model_quant.tflite
  - assets/labels.txt